"""3 Make phone colunm unique

Revision ID: b76ed37268be
Revises: 0a69912ebc11
Create Date: 2025-09-27 19:08:52.227171

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b76ed37268be'
down_revision: Union[str, Sequence[str], None] = '0a69912ebc11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('active', sa.Boolean(), nullable=False))
    op.create_unique_constraint(op.f('uq_users_phone'), 'users', ['phone'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_users_phone'), 'users', type_='unique')
    op.drop_column('users', 'active')
    # ### end Alembic commands ###
